name: Run tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --output /tmp/nupkgs

      - name: Install tool
        run: dotnet tool install --global --source /tmp/nupkgs --prerelease ProjectDiff.Tool

      - name: Run tool
        run: dotnet-project-diff ProjectDiff.sln --format json
